language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel 
  - docker tag udagram-api-feed mamaafrica/udagram-api-feed:latest
  - docker tag udagram-api-user mamaafrica/udagram-api-user:latest
  - docker tag udagram-frontend mamaafrica/udagram-frontend:latest
  - docker tag udagram-reverseproxy mamaafrica/udagram-reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mamaafrica/udagram-api-feed
  - docker push mamaafrica/udagram-api-user
  - docker push mamaafrica/udagram-frontend
  - docker push mamaafrica/udagram-reverseproxy
