apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    run: backend-user
spec:
  selector:
    app: backend-user
    run: backend-user
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
