apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    run: backend-feed
spec:
  selector:
    app: backend-feed
    run: backend-feed
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
