apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: mamaafrica/udagram-frontend
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
             secretKeyRef:
                name: env-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USERNAME
            valueFrom:
             secretKeyRef:
                name: env-secret
                key: POSTGRES_USERNAME
          - name: POSTGRES_HOST
            valueFrom:
             configMapKeyRef:
                name: env-configmap
                key: POSTGRES_HOST
          - name: POSTGRES_DB
            valueFrom:
             configMapKeyRef:
                name: env-configmap
                key: POSTGRES_DB
          - name: AWS_BUCKET
            valueFrom:
             configMapKeyRef:
                name: env-configmap
                key: AWS_BUCKET
          - name: AWS_REGION
            valueFrom:
             configMapKeyRef:
                name: env-configmap
                key: AWS_REGION
          - name: JWT_SECRET
            valueFrom:
             configMapKeyRef:
                name: env-configmap
                key: JWT_SECRET
          - name: AWS_PROFILE
            valueFrom:
             configMapKeyRef:
                name: env-configmap
                key: AWS_PROFILE

