apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: mamaafrica/reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        restartPolicy: Always
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
             secretKeyRef:
                name: env-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
             secretKeyRef:
                name: env-secret
                key: POSTGRES_USER
          - name: POSTGRES_HOST
            valueFrom:
             configMapKeyRef:
                name: env-configmap
                key: POSTGRES_HOST
          - name: POSTGRES_DB
            valueFrom:
             configMapKeyRef:
                name: env-configmap
                key: POSTGRES_DB
          - name: AWS_BUCKET
            valueFrom:
             configMapKeyRef:
                name: env-configmap
                key: AWS_BUCKET
          - name: AWS_REGION
            valueFrom:
             configMapKeyRef:
                name: env-configmap
                key: AWS_REGION
          - name: JWT_SECRET
            valueFrom:
             configMapKeyRef:
                name: env-configmap
                key: JWT_SECRET
          - name: AWS_PROFILE
            valueFrom:
             configMapKeyRef:
                name: env-configmap
                key: AWS_PROFILE